# -*- coding: utf-8 -*-
"""Schedulev3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hqrC4SUwfbAQyhgx0ubAgC9IXn9yj6xE
"""



"""Patient / Doctor Scheduler - Create a patient class and a doctor class. Have a doctor that can handle multiple patients and setup a scheduling program where a doctor can only handle 16 patients during an 8 hr work day."""

timeslot = {'9:00':'Bo','9:30':''}

class Patient:
  def __init__(self, firstName, time):
    self.firstName = firstName
    self.time = time

  def __str__(self):
    return f'{self.firstName}'

  def alreadyScheduled(self, doctor):
    if self.firstName in doctor.timeslot.values():
      return True

class Doctor():
  def __init__(self,firstName, timeslot):
    self.firstName = firstName
    self.timeslot = timeslot

  def available(self, patient):
    if patient.firstName not in self.timeslot.values() and self.timeslot[patient.time]=='':
      self.timeslot[patient.time] = patient.firstName.capitalize()
      return True

  def noSpotLeft(self):
    if '' not in self.timeslot.values():
      return True

  
  def appointmentTaken(self, patient):
    if patient.firstName not in self.timeslot.values() and self.timeslot[patient.time] != patient.firstName and '' in self.timeslot.values():
      return True
  

  def __str__(self):
    return f'{self.firstName}'
  def __repr__(self):
    return f'{self.firstName} is selected'


def insertTime(doctor):
  global time
  
  while True:
    if time not in doctor.timeslot.keys():
      time = input('input the correct time: ')
      return time
    else:
      break  

def selectDoctor(doctorList):
  global doctor
  
  print('Please enter the id of the doctor that you would like to see: ')
  for i in range(len(doctorList)):
    print(f'{i+1}. {doctorList[i]}')

  identity = int(input())-1
  doctor = doctorList[identity]
  return doctor

jill = Doctor('Dr. Jill', timeslot)
ken = Doctor('Dr. Ken', timeslot)
doctorList = [jill, ken]
selectDoctor(doctorList)

print(f'{doctor} has these dates available: ')
for k,v in  doctor.timeslot.items():
  if v == '':
    print(k)

pName = input('What is your first name? ')
time = input('What time do you want to schedule your appointment? ')
insertTime(doctor)
patient = Patient(pName, time)

if patient.alreadyScheduled(doctor):
  for k,v in doctor.timeslot.items():
    if v == patient.firstName:
      print(f'{v} already scheduled an appointment at {k}')

if doctor.noSpotLeft():
  print(f'{doctor} has no more available appointment')

if doctor.available(patient):
  print(f'{patient} is selected to see {doctor} at {time}')

while True:
  if doctor.appointmentTaken(patient):
    print('this time is not avaliable. We have these times open:')
    for k,v in  doctor.timeslot.items():
      if v == '':
        print(k)
    patient.time = input('input another time: ')
    if doctor.timeslot[patient.time] == '':
      doctor.timeslot[patient.time] = patient.firstName.capitalize()
  else:
    break

